parameters:
  terraformWorkspacePrefix: ''
  environmentName: ''
  enablePrIsolation: true
  stepName: ''

steps:
  - task: Bash@3
    name: ${{ parameters.stepName }}
    displayName: Compute and output pipeline variable for Terraform Workspace
    env:
      TERRAFORM_WORKSPACE_PREFIX: ${{ parameters.terraformWorkspacePrefix }}
      ENVIRONMENT_NAME: ${{ parameters.environmentName }}
      PR_ISOLATION: ${{ parameters.enablePrIsolation }}
    inputs:
      targetType: 'inline'
      script: |
        #!/usr/bin/env bash

        # Parses the PullRequest number from sourcebranch, if this is a PR build. Otherwise
        # produces a simple combination of prefix+environment to be used as the workspace name.

        PR_NUMBER=""
        if [[ $PR_ISOLATION == true ]]; then

            # BUILD_SOURCEBRANCH will look like "refs/pull/1/merge" if this is a PR branch
            IFS='/' # delimiter
            read -ra PARTS <<< "$BUILD_SOURCEBRANCH" # split the branch into parts

            if [[ "${#PARTS[@]}" == "4" && "${PARTS[0]}" == "refs" && "${PARTS[1]}" == "pull" && "${PARTS[3]}" == "merge" ]]; then
                PR_NUMBER="${PARTS[2]}"
            fi
        fi

        OUTVAR=""
        if [[ "$PR_NUMBER" != "" ]]; then
            if [[ "$TERRAFORM_WORKSPACE_PREFIX" != "" ]]; then
                OUTVAR="pr$PR_NUMBER-$TERRAFORM_WORKSPACE_PREFIX"
            else
                OUTVAR="pr$PR_NUMBER"
            fi
        else
            if [[ "$TERRAFORM_WORKSPACE_PREFIX" != "" ]]; then
                OUTVAR="$TERRAFORM_WORKSPACE_PREFIX-$ENVIRONMENT_NAME"
            else
                OUTVAR="$ENVIRONMENT_NAME"
            fi
        fi

        echo "BUILD_SOURCEBRANCH: $BUILD_SOURCEBRANCH"
        echo "TERRAFORM_WORKSPACE_PREFIX: $TERRAFORM_WORKSPACE_PREFIX"
        echo "ENVIRONMENT_NAME: $ENVIRONMENT_NAME"
        echo "PR_ISOLATION: $PR_ISOLATION"
        echo "PR_NUMBER: $PR_NUMBER"
        echo "OUTVAR: $OUTVAR"
        echo "##vso[task.setvariable variable=TF_WORKSPACE_NAME;isOutput=true]$OUTVAR"

        exit 0