steps:
  - task: AzureCLI@1
    displayName: 'Apply Resource Changes to Environment'
    env:
      TF_VAR_remote_state_container: $(REMOTE_STATE_CONTAINER)
      TF_VAR_remote_state_account: $(REMOTE_STATE_ACCOUNT)
    inputs:
      azureSubscription: '$(SERVICE_CONNECTION_NAME)'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
        #!/usr/bin/env bash

        set -euo pipefail
        set -o nounset

        function storageAccountPrimaryKey() {
            az storage account keys list --subscription "$ARM_SUBSCRIPTION_ID" --account-name "$TF_VAR_remote_state_account" --query "[0].value" --output tsv
        }

        function azureTenantId() {
            az account show --query "tenantId" --output tsv
        }

        function terraformVersionCheck() {
            if [[ $(which terraform) && $(terraform --version | head -n1 | cut -d" " -f2 | cut -c 2\-) == $TF_VERSION ]]; then
                echo "Terraform version check completed"
              else
                TF_ZIP_TARGET="https://releases.hashicorp.com/terraform/$TF_VERSION/terraform_${TF_VERSION}_linux_amd64.zip"
                echo "Info: installing $TF_VERSION, target: $TF_ZIP_TARGET"
        
                wget $TF_ZIP_TARGET -q
                unzip -q "terraform_${TF_VERSION}_linux_amd64.zip"
                sudo mv terraform /usr/local/bin
                rm *.zip
            fi
            
            terraform -version

            # Assert that jq is available, and install if it's not
            command -v jq >/dev/null 2>&1 || { echo >&2 "Installing jq"; sudo apt install -y jq; }
        }

        terraformVersionCheck

        cd $TF_TEMPLATE_WORKING_DIR

        # Setting the scripts to be run as executable
        chmod -R 752 .terraform

        export ARM_ACCESS_KEY=$(storageAccountPrimaryKey)
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_TENANT_ID=$(azureTenantId)

        TF_PLAN_FILE="${TF_WORKSPACE_NAME}_plan.out"
        TF_CLI_ARGS=${TF_CLI_ARGS:-}

        terraform apply $TF_CLI_ARGS -input=false -auto-approve $TF_PLAN_FILE
