steps:
  - task: AzureCLI@1
    displayName: 'Create Terraform Execution Plan'
    env:
      TF_VAR_remote_state_container: $(REMOTE_STATE_CONTAINER)
      TF_VAR_remote_state_account: $(REMOTE_STATE_ACCOUNT)
    inputs:
      azureSubscription: '$(SERVICE_CONNECTION_NAME)'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
        #!/usr/bin/env bash

        set -euo pipefail
        set -o nounset

        function storageAccountPrimaryKey() {
            az storage account keys list --subscription "$ARM_SUBSCRIPTION_ID" --account-name "$TF_VAR_remote_state_account" --query "[0].value" --output tsv
        }

        function azureTenantId() {
            az account show --query "tenantId" --output tsv
        }

        cd $TF_TEMPLATE_WORKING_DIR

        # Clear all previous plans
        rm -f *.out
        # Setting the scripts to be run as executable
        chmod -f 752 *.sh || true

        export ARM_ACCESS_KEY=$(storageAccountPrimaryKey)
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_TENANT_ID=$(azureTenantId)

        TF_PLAN_FILE="${TF_WORKSPACE_NAME}_plan.out"
        TF_CLI_ARGS=${TF_CLI_ARGS:-}

        terraform plan $TF_CLI_ARGS -out $TF_PLAN_FILE
