parameters:
  environment: ''
  configurationMatrix: []
  forceRun: false
  skipTests: false

jobs:

- job: TemplateChangeDetection
  variables:
  - group: '${{ parameters.environment }} Environment Variables'
  displayName: Determine CI Targets to Run
  pool: $(AGENT_POOL)
  condition: not(coalesce(variables.FORCE_RUN, ${{ parameters.forceRun }}))

  steps:
  - ${{ each config in parameters.configurationMatrix }}:
    - template: scripts/set-cicd-flag.yml
      parameters:
        terraformTemplatePath: ${{ config.terraformTemplatePath }}
        jobName: ${{ config.jobName }}

- ${{ each config in parameters.configurationMatrix }}:
  - job: Build_${{ config.jobName }}_${{ parameters.environment }}_ComputeWs
    dependsOn: TemplateChangeDetection
    pool: $(AGENT_POOL)
    condition: or(coalesce(variables.FORCE_RUN, ${{ parameters.forceRun }}), eq(dependencies.TemplateChangeDetection.outputs['${{ config.jobName }}.needs_cicd'], 'true'))
    
    steps:
    - template: scripts/compute-workspace.yml
      parameters:
        terraformWorkspacePrefix: ${{ config.terraformWorkspacePrefix }}
        environmentName: ${{ parameters.environment }}
        stepName: ComputeWs

  - job: Build_${{ config.jobName }}_${{ parameters.environment }}
    dependsOn: Build_${{ config.jobName }}_${{ parameters.environment }}_ComputeWs
    pool: $(AGENT_POOL)

    variables:
    - group: '${{ parameters.environment }} Environment Variables'

    - name: TF_WORKSPACE_NAME
      value: $(dependencies.Build_${{ config.jobName }}_${{ parameters.environment }}_ComputeWs_Step.outputs['ComputeWs.TF_WORKSPACE_NAME'])

    - name: ARTIFACT_ROOT
      value: '$(System.DefaultWorkingDirectory)/$(BUILD_ARTIFACT_NAME)'

    - name: TERRAFORM_TEMPLATE_PATH
      value: ${{ config.terraformTemplatePath }}

    - name: TF_TEMPLATE_WORKING_DIR
      value: '$(System.DefaultWorkingDirectory)/$(BUILD_ARTIFACT_NAME)/${{ config.terraformTemplatePath }}'

    workspace:
      clean: all

    steps:
    - checkout: none
    - download: none

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: $(BUILD_ARTIFACT_NAME)
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: GoTool@0
      displayName: 'Verify Go Version is Installed'
      inputs:
        version: '$(GO_VERSION)'

    - task: Bash@3
      name: SetupGitCredentialInjection
      displayName: Configure Git to use PAT
      condition: ne(variables.TEMPLATE_REPO_PAT, '')
      inputs:
        targetType: 'inline'
        script: '[[ -z $SecretPAT ]] && echo "No PAT provided; skipping." || git config --global url."https://cobalt:$SecretPAT@".insteadOf "https://"'
      env:
        SecretPAT: $(TEMPLATE_REPO_PAT)

    - template: scripts/test-unit.yml
      parameters:
        skip: ${{ parameters.skipTests }}

    - template: scripts/tf-create-workspace.yml

    - task: Bash@3
      name: TeardownGitCredentialInjection
      displayName: Reset Git configuration
      condition: and(always(), ne(variables.TEMPLATE_REPO_PAT, ''))
      inputs:
        targetType: 'inline'
        script: '[[ -z $SecretPAT ]] && echo "No PAT provided; skipping." || git config --global --unset url."https://cobalt:$SecretPAT@".insteadOf'
      env:
        SecretPAT: $(TEMPLATE_REPO_PAT)

    - template: scripts/tf-generate-plan.yml

    - task: CopyFiles@2
      displayName: Copy Build Directory to Artifact Directory
      inputs:
        contents: '**'
        sourceFolder: '$(System.DefaultWorkingDirectory)/$(BUILD_ARTIFACT_NAME)'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        parallel: true
        parallelCount: 8
        artifactName: '$(BUILD_ARTIFACT_NAME)-$(TF_WORKSPACE_NAME)'
        pathToPublish: $(Build.ArtifactStagingDirectory)
