jobs:
- job: Publish
  pool: $(AGENT_POOL)

  workspace:
    clean: all

  steps:
  - task: CopyFiles@2
    displayName: Copy Pipeline Scripts to Artifact Directory
    inputs:
      contents: $(PIPELINE_ROOT_DIR)/**/*
      sourceFolder: $(Build.SourcesDirectory)
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: CopyFiles@2
    displayName: Copy Terraform Directory to Artifact Directory
    inputs:
      contents: $(TF_ROOT_DIR)/**/*
      sourceFolder: $(Build.SourcesDirectory)
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: CopyFiles@2
    displayName: Copy Test Harness to Artifact Directory
    inputs:
      contents: $(TEST_HARNESS_DIR)/**/*
      sourceFolder: $(Build.SourcesDirectory)
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: CopyFiles@2
    displayName: Copy Go Mod/Sum to Artifact Directory
    inputs:
      contents: go.*
      sourceFolder: $(Build.SourcesDirectory)
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      parallel: true
      parallelCount: 8
      artifactName: '$(BUILD_ARTIFACT_NAME)'
      pathToPublish: $(Build.ArtifactStagingDirectory)